"""
This family file was auto-generated by generate_family_file.py script.

Configuration parameters:
  url = https://ultiblocks.miraheze.org/
  name = ultiblocks

Please do not commit this to the Git repository!
"""
from pywikibot import family


class Family(family.Family):  # noqa: D101

    name = 'ultiblocks'
    langs = {
        'en': 'ultiblocks.miraheze.org',
    }

    def scriptpath(self, code):
        return {
            'en': '/w',
        }[code]

    def protocol(self, code):
        return {
            'en': 'https',
        }[code]
